export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL'
export const ADD_TODO_RESET = 'ADD_TODO_RESET'

export const LIST_TODO_REQUEST = 'LIST_TODO_REQUEST'
export const LIST_TODO_SUCCESS = 'LIST_TODO_SUCCESS'
export const LIST_TODO_FAIL = 'ADD_TODO_FAIL'
export const LIST_TODO_RESET = 'LIST_TODO_RESET'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL'
export const UPDATE_TODO_RESET = 'UPDATE_TODO_RESET'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL'
export const DELETE_TODO_RESET = 'DELETE_TODO_RESET'

export const DETAIL_TODO_REQUEST = 'DETAIL_TODO_REQUEST'
export const DETAIL_TODO_SUCCESS = 'DETAIL_TODO_SUCCESS'
export const DETAIL_TODO_FAIL = 'DETAIL_TODO_FAIL'
export const DETAIL_TODO_RESET = 'DETAIL_TODO_RESET'

